// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SymptomScout.API.Persistence;

#nullable disable

namespace SymptomScout.API.Migrations
{
    [DbContext(typeof(SymptomScoutDbContext))]
    [Migration("20230622072404_Create")]
    partial class Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SymptomScout.Shared.Domain.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosisId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DiagnosisId");

                    b.HasIndex(new[] { "Name" }, "UC_Diagnosis__Name")
                        .IsUnique();

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("SymptomScout.Shared.Domain.Symptom", b =>
                {
                    b.Property<int>("SymptomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SymptomId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SymptomId");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex(new[] { "Name" }, "UC_Symptom_Name")
                        .IsUnique();

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("SymptomScout.Shared.Domain.Symptom", b =>
                {
                    b.HasOne("SymptomScout.Shared.Domain.Diagnosis", null)
                        .WithMany("Symptoms")
                        .HasForeignKey("DiagnosisId");
                });

            modelBuilder.Entity("SymptomScout.Shared.Domain.Diagnosis", b =>
                {
                    b.Navigation("Symptoms");
                });
#pragma warning restore 612, 618
        }
    }
}
